name: domovina_wallet
description: "DOMOVINA Wallet â€” self-custody Solana wallet for Croatian users"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  http: ^1.0.0
  solana: ^0.31.2+1
  ed25519_hd_key: ^2.0.0
  bip39: ^1.0.0
  cryptography: ^2.0.0
  flutter_secure_storage: ^10.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: ^6.1.2
  firebase_core: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/Croatian_shield_checkerboard_minimal_logo_red__blue__white_1766532723985.png
  remove_alpha_ios: true
